name: genomics-alignment
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  # Core dependencies
  - python=3.9
  - pip
  
  # Workflow managers
  - nextflow=22.10.6
  - snakemake=7.24.0
  
  # Quality control tools
  - fastqc=0.11.9
  - multiqc=1.13
  
  # Trimming tools
  - trimmomatic=0.39
  
  # Alignment tools
  - bwa=0.7.17
  - bowtie2=2.4.5
  - minimap2=2.24
  
  # SAM/BAM processing
  - samtools=1.15
  - sambamba=0.8.2
  - picard=2.27.4
  
  # Variant calling
  - gatk4=4.2.6.1
  - bcftools=1.15
  - freebayes=1.3.6
  
  # Utilities
  - pandas=1.5.2
  - numpy=1.23.5
  - matplotlib=3.6.2
  - seaborn=0.12.2
  - pyyaml=6.0
  - biopython=1.80
  
  # File management
  - pigz=2.6
  - parallel=20220722
  
  # Python packages
  - pip:
    - pyfastx==0.8.4
    - nanoplot==1.41.0
    - cutadapt==4.2