version: '3.8'

services:
  pii-monitor:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ML_ENABLED=true
      - CONFIDENCE_THRESHOLD=0.8
      - RATE_LIMIT_POINTS=100
      - RATE_LIMIT_DURATION=60
    volumes:
      # Mount credentials and models for persistence
      - ./credentials.json:/app/credentials.json:ro
      - ./token.json:/app/token.json:ro
      - ./ml/models:/app/ml/models
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add Redis for rate limiting in production
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

# volumes:
#   redis_data: 